### ISSUE TITLE
Subclassing QOdooModel

### ISSUE THREAD

**Issue by horlich** [planed-es/QtOdoo#1]
Subclassing QOdooModel causes a linker error because method QOdooModel::Property::loadFromVariant cannot be found.
A fix would be adding QTODOO_LIBRARY_EXPORT to declaration of QOdooModel::Property and subclasses.

**Comment by Plaristote** [comment]
I am suspecting the dllexport/import instructions should go on the `QOdooModel::Property::StringProperty` and `QOdooModel::Property::IdProperty` classes, since `QOdooModel::Property` is a template class (there's nothing from a dll to export), and doesn't provide `loadFromVariant` anyway.

I'm a bit surprised, but I've been looking up some documentation, and it does seem like these classes need to be exported, despite being nested within a class that's already exported. The oddities of Microsoft's C++ extensions never cease to catch me off guard !

I've pushed #b016bbe3596 which should fix the issue. I can't really tell for sure at the moment, as I don't have a Windows machine at hand to put it to the test. Can you confirm that it works ?

**Comment by horlich** [comment]
It is now linking properly. Thank you.
